apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: order-updater-service
  name: order-updater-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: order-updater-service
    spec:
      containers:
      - image: order-updater-service
        name: order-updater
        ports:
        - containerPort: 8005
        resources: {}
      restartPolicy: Always
status: {}
