apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: restaurant-service
  name: restaurant-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: restaurant-service
    spec:
      containers:
      - image: restaurant-service:0.1
        name: restaurant
        ports:
        - containerPort: 8001
        resources: {}
      restartPolicy: Always
status: {}
